### PR TITLE
Auto-generate BOM

### PR DESCRIPTION
**Pull request by gastaldi**
/cc @dmlloyd @radcortez 

This removes the BOM module to make sure the BOM resolves only the smallrye-common artifacts

### CODE REVIEW

**Comment by gastaldi** [comment]
Crap, the formatter plugin is invoked directly, shouldn't be doing that in a BOM project :disappointed:

**Comment by dmlloyd** [comment]
What does the generated BOM look like?

**Comment by gastaldi** [comment]
```xml
<?xml version='1.0' encoding='UTF-8'?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">


    <modelVersion>4.0.0</modelVersion>

    <groupId>io.smallrye.common</groupId>
    <artifactId>smallrye-common-bom</artifactId>
    <version>1.3.1-SNAPSHOT</version>
    <name>Smallrye Common: BOM</name>
    <packaging>pom</packaging>
    <description>Bill of material</description>
    
        <url>http://smallrye.io</url>    
        <licenses>
            <license>
                <name>Apache License, Version 2.0</name>
                <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
                <distribution>${l.distribution}</distribution>
            </license>
        </licenses>
    
    
        <scm>
            <connection>scm:git:git@github.com:smallrye/smallrye-common.git</connection>
            <developerConnection>scm:git:git@github.com:smallrye/smallrye-common.git</developerConnection>
            <url>scm:git:git@github.com:smallrye/smallrye-common.git</url>
            <tag>HEAD</tag>
        </scm>
    
            <developers>
            <developer>
                <id>${d.id}</id>
                <name>Ken Finnigan</name>
                <email>ken@kenfinnigan.me</email>
                <organization>Red Hat</organization>
                <organizationUrl>https://www.redhat.com/en</organizationUrl>
            </developer>
        </developers>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.smallrye.common</groupId>
                <artifactId>smallrye-common-annotation</artifactId>
                <version>1.3.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.smallrye.common</groupId>
                <artifactId>smallrye-common-classloader</artifactId>
                <version>1.3.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.smallrye.common</groupId>
                <artifactId>smallrye-common-constraint</artifactId>
                <version>1.3.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.smallrye.common</groupId>
                <artifactId>smallrye-common-cpu</artifactId>
                <version>1.3.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.smallrye.common</groupId>
                <artifactId>smallrye-common-function</artifactId>
                <version>1.3.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.smallrye.common</groupId>
                <artifactId>smallrye-common-expression</artifactId>
                <version>1.3.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.smallrye.common</groupId>
                <artifactId>smallrye-common-net</artifactId>
                <version>1.3.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.smallrye.common</groupId>
                <artifactId>smallrye-common-io</artifactId>
                <version>1.3.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.smallrye.common</groupId>
                <artifactId>smallrye-common-version</artifactId>
                <version>1.3.1-SNAPSHOT</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
    
        <build>
            <pluginManagement>
                <plugins>
                </plugins>
            </pluginManagement>
        </build>
    
</project>
```

**Comment by dmlloyd** [comment]
So I guess it's inheriting the developer info from the SmallRye parent?  And what's the deal with the `${d.id}` and `${l.distribution}` properties?  The `description` isn't so great. Also it would be nice if the dependency versions were just `${project.version}` but I guess that's not super important when the BOM is generated.

Still though, I don't know that this has any major advantages over just having the BOM be manual.

**Comment by gastaldi** [comment]
> So I guess it's inheriting the developer info from the SmallRye parent? 

Yes 

> And what's the deal with the `${d.id}` and `${l.distribution}` properties? 

I have no idea, I'll check it out

> The `description` isn't so great. 

That can be customized in the plugin, I'll do that

> Still though, I don't know that this has any major advantages over just having the BOM be manual.

I guess it saves you the trouble of having to manually add to it if a new module is introduced, so IMHO it's definitely a good thing :wink:

**Comment by gastaldi** [comment]
I created https://github.com/smallrye/smallrye-parent/pull/162 to add the missing info in smallrye-parent, but I think it's better to override the `<developers>` in this case

**Comment by gastaldi** [comment]
Apparently the description is fixed in the generated template, I fixed in https://github.com/sundrio/sundrio/pull/169

This is what the generated BOM now looks like: 

```xml
<?xml version='1.0' encoding='UTF-8'?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">


    <modelVersion>4.0.0</modelVersion>

    <groupId>io.smallrye.common</groupId>
    <artifactId>smallrye-common-bom</artifactId>
    <version>1.3.1-SNAPSHOT</version>
    <name>Smallrye Common: BOM</name>
    <packaging>pom</packaging>
    <description>Bill of material</description>
    
        <url>http://smallrye.io</url>    
        <licenses>
            <license>
                <name>Apache License, Version 2.0</name>
                <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
                <distribution>repo</distribution>
            </license>
        </licenses>
    
    
        <scm>
            <connection>scm:git:git@github.com:smallrye/smallrye-common.git</connection>
            <developerConnection>scm:git:git@github.com:smallrye/smallrye-common.git</developerConnection>
            <url>scm:git:git@github.com:smallrye/smallrye-common.git</url>
            <tag>HEAD</tag>
        </scm>
    
            <developers>
            <developer>
                <id>smallrye-common-team</id>
                <name>SmallRye Common Team</name>
                <organization>smallrye-common</organization>
                <organizationUrl>https://smallrye.io/</organizationUrl>
            </developer>
        </developers>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.smallrye.common</groupId>
                <artifactId>smallrye-common-annotation</artifactId>
                <version>1.3.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.smallrye.common</groupId>
                <artifactId>smallrye-common-classloader</artifactId>
                <version>1.3.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.smallrye.common</groupId>
                <artifactId>smallrye-common-constraint</artifactId>
                <version>1.3.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.smallrye.common</groupId>
                <artifactId>smallrye-common-cpu</artifactId>
                <version>1.3.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.smallrye.common</groupId>
                <artifactId>smallrye-common-function</artifactId>
                <version>1.3.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.smallrye.common</groupId>
                <artifactId>smallrye-common-expression</artifactId>
                <version>1.3.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.smallrye.common</groupId>
                <artifactId>smallrye-common-net</artifactId>
                <version>1.3.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.smallrye.common</groupId>
                <artifactId>smallrye-common-io</artifactId>
                <version>1.3.1-SNAPSHOT</version>
            </dependency>
            <dependency>
                <groupId>io.smallrye.common</groupId>
                <artifactId>smallrye-common-version</artifactId>
                <version>1.3.1-SNAPSHOT</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
    
        <build>
            <pluginManagement>
                <plugins>
                </plugins>
            </pluginManagement>
        </build>
    
</project>

```

**Comment by radcortez** [comment]
A couple of questions:

- Can't we just get rid of the empty build/pluginManagement section?
- What is `skipStagingRepositoryClose`?

**Comment by gastaldi** [comment]
> A couple of questions:
> 
> * Can't we just get rid of the empty build/pluginManagement section?

For some reason the template doesn't remove it: 

> * What is `skipStagingRepositoryClose`?

**Review by dmlloyd — APPROVED** [review]
I guess I'm OK with this.

**Pull request merged**
