### PR TITLE
Move baseline to Java 17

### LINKED ISSUE #348: Move to Java 17 as a baseline requirement
It's time. (Is it time?)

### PR DESCRIPTION
**Pull request by dmlloyd**
Fixes #348, and some other minor issues as well

### CODE REVIEW

**Review by radcortez — APPROVED** [review]

**Comment by radcortez** [comment]
Please wait until next week for our SR meeting so we can also discuss this there.

**Comment by dmlloyd** [comment]
Any update?

**Comment by radcortez** [comment]
We can move once we make final releases to support MP 7.0. Not all implementations are required, but it probably wouldn't hurt to have all components to make a final release with 11 before moving to 17.

**Comment by radcortez** [comment]
Maybe we should do a Parent update to 17 first, release, and then here?

**Comment by dmlloyd** [comment]
The parent doesn't really need to change until there are no consumers left which rely on 11 AFAICT. I don't think it makes sense to block on it at any rate.

**Comment by dmlloyd** [comment]
Now that 2.8.0 was released, what do we think about moving this forward?

**Comment by dmlloyd** [comment]
Per conversations, I'm going ahead with this. If there is a specific problem, please let me know (I'm on Zulip).

**Pull request merged**
