### PR TITLE
Require Java 11 (minimum) at run time

### PR DESCRIPTION
**Pull request by dmlloyd**
Flatten all pre-11 source directories.

### CODE REVIEW

**Comment by radcortez** [comment]
> Any thoughts on this?

Can it wait for SR Commons 2.0 (with the Jakarta move?)

**Comment by dmlloyd** [comment]
> > Any thoughts on this?
> 
> Can it wait for SR Commons 2.0 (with the Jakarta move?)

Maybe; could you remind me what the timeline for that is expected to be?

**Comment by radcortez** [comment]
We already have RCs for SR Commons 2.0. We can do the Final anytime, but we are delaying it until Wildfly / Quarkus also go Final with the Jakarta update. At this point, it seems that Jakarta 10 will go out by the end Q2, so maybe we need a Final in the next few weeks for Wildfly.

**Comment by dmlloyd** [comment]
We should also make sure #158 is done before releasing; all we're waiting for now is a `jboss-logging` release.

**Review by radcortez — DISMISSED** [review]

**Comment by radcortez** [comment]
Let's hold this for SR Commons 2.0.

**Comment by radcortez** [comment]
This PR is merged every time we update the `jakarta` branch.

**Comment by radcortez** [comment]
Rebased in the `jakarta` branch and added to `main`.

**Pull request closed without merging**
