### PR TITLE
Introduce CPU module

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by dmlloyd** [comment]
Well, that's a problem.

The MR JAR support requires a JBoss fork of the `maven-compiler-plugin`.

**Comment by kenfinnigan** [comment]
where's the forked version live?

do we need to add JBoss Repo? Is it ok for us to use that forked version upstream?

**Comment by dmlloyd** [comment]
The forked version is at https://github.com/jboss/maven-compiler-plugin.

**Comment by dmlloyd** [comment]
Maybe we could use some more voices shouting about https://issues.apache.org/jira/browse/MCOMPILER-320 to move things along.

**Pull request merged**
