### PR TITLE
Introduce reference support submodule

### PR DESCRIPTION
**Pull request by dmlloyd**
This would replace usages of `wildfly-common`'s `ref` subpackage.

### CODE REVIEW

**Review by radcortez — DISMISSED** [review]

**Comment by dmlloyd** [comment]
Updated to use signed commits.

**Comment by dmlloyd** [comment]
I don't understand the Windows failure. It's happening during BOM generation.

**Comment by radcortez** [comment]
Strange, the previous build seems ok. I don't see a reason for that error either.

**Comment by dmlloyd** [comment]
The `memento` method and its corresponding class were added in Maven 3.3.0, according to the JavaDoc.

**Comment by dmlloyd** [comment]
I can only speculate that the Maven version on the Windows node was recently updated, and that `sundr` isn't compatible. I'm trying to verify that now.

**Comment by dmlloyd** [comment]
Confirmed. Works with `3.8.2`, fails with `3.8.5`.

**Comment by dmlloyd** [comment]
https://github.com/sundrio/sundrio/issues/309

**Review by radcortez — APPROVED** [review]

**Comment by radcortez** [comment]
> Here's an idea for a workaround [using Maven wrappers](https://github.com/actions/setup-java/issues/40#issuecomment-1000724522).

Updated the workflows to use the maven wrapper, so the build passes now.

Feel free to merge the PR :)

**Pull request merged**
