### PR TITLE
Support multiple nesting of JAR files

### LINKED ISSUE #289: Doesn't work in Spring Boot jar
Spring BootJar has complex layout and special spring ClassLoader to make it work
SmallRye Config doesn't work in Spring Application packed as spring bootJar.

I have found, the problem is in your class
`io.smallrye.common.classloader.ClassPathUtils`

Full explanation and fix:
https://github.com/smallrye/smallrye-config/issues/1101

PS: more advanced research and fix are welcome 🙏

### PR DESCRIPTION
**Pull request by dmlloyd**
* Make sure that `jar:file:///...` are properly formed (the sub-URL must have a scheme of `file`)
* When there is no `!` in the JAR URL, treat the file as a JAR and process its root path
* Otherwise recursively resolve each segment which is `!`-terminated

Fixes #289

### CODE REVIEW

**Comment by dmlloyd** [comment]
One thing I am unsure of is whether it is correct to treat URLs of form `jar:file:///some/path/something.jar` as valid (current behavior) or invalid.

**Comment by magicprinc** [comment]
TestApp still fails 😭
https://github.com/magicprinc/SmallRyeConfig-SpringBoot/tree/fix2

I have put your classes inside the app removed jar with original classes.
You can debug and see details

**Comment by dmlloyd** [comment]
Do you know what URL was input into the method?

**Comment by magicprinc** [comment]
`jar:file:/D:/TEMP/SmallRyeConfig-SpringBoot/build/libs/SmallRyeConfig-SpringBoot-1.0.jar!/BOOT-INF/classes!/application.properties`

**Comment by magicprinc** [comment]
https://github.com/magicprinc/SmallRyeConfig-SpringBoot/tree/fixBundled

url: `jar:file:/D:/TEMP/SmallRyeConfig-SpringBoot/build/libs/SmallRyeConfig-SpringBoot-1.0.jar!/BOOT-INF/classes!/application.properties`

file: `file:/D:/TEMP/SmallRyeConfig-SpringBoot/build/libs/SmallRyeConfig-SpringBoot-1.0.jar!/BOOT-INF/classes!/application.properties`

jar: `D:\TEMP\SmallRyeConfig-SpringBoot\build\libs\SmallRyeConfig-SpringBoot-1.0.jar`

localPath: `/BOOT-INF/classes!/application.properties`

**Comment by dmlloyd** [comment]
Can you determine whether the sub-entry `/BOOT-INF/classes` inside of `file:///D:/TEMP/SmallRyeConfig-SpringBoot/build/libs/SmallRyeConfig-SpringBoot-1.0.jar` is a JAR directory, or is it a nested JAR file? I am assuming that `!` means to treat that entry as a JAR file but Spring Boot might not agree with that, but this would be an easy way to check.

**Comment by magicprinc** [comment]
image

**Comment by magicprinc** [comment]
image

**Comment by magicprinc** [comment]
image

**Comment by dmlloyd** [comment]
One more fix to prevent wrong path lookups if the `!` is followed by a `/`.

**Comment by magicprinc** [comment]
Works!

jarPath: `D:\TEMP\SmallRyeConfig-SpringBoot\build\libs\SmallRyeConfig-SpringBoot-1.0.jar`
path: `/BOOT-INF/classes!/application.properties`
→
localPath: `/BOOT-INF/classes`
path: `/BOOT-INF/classes!/application.properties`

**Comment by magicprinc** [comment]
BTW, sorry for a noob question...
Why do you need such heavy machinery (FileSystems, path parsing)
As far as I know Spring uses only ClassLoader#getResources and url.openStream()

**Comment by dmlloyd** [comment]
That's a more complex question than it seems to be ;)

There are several answers though:

* Sometimes there is no class loader for the target path
* Sometimes the class loader does not have the necessary capabilities
* Sometimes you are using an API that is based on `Path`
* Probably more cases I'm not thinking of right now

**Comment by magicprinc** [comment]
When is it possible to have snapshot/RC version in maven repo? 😥🙏

**Comment by dmlloyd** [comment]
I'm just doing some final testing with Quarkus to make sure nothing has broken.

**Pull request merged**
