### PR TITLE
Use AdoptOpenJDK's Java setup

### PR DESCRIPTION
**Pull request by dmlloyd**
This allows us to have a consistent & functional env var for the JDK installation.

### CODE REVIEW

**Comment by radcortez** [comment]
Hum, maybe you want to use the one from @cescoffier :)

https://github.com/marketplace/actions/setup-java-using-binaries-from-adoptopenjdk

**Comment by cescoffier** [comment]
Nope, you want the one provided by adoptOpenJdk.

**Comment by dmlloyd** [comment]
We need to be able to specify an env var for the JDK release, and setup-java and most of its derivatives don't support that.

**Comment by dmlloyd** [comment]
I proposed fix for the Jacoco problem in smallrye/smallrye-parent#148.

**Comment by cescoffier** [comment]
@dmlloyd you can use a matrix as I did for mutiny:
https://github.com/smallrye/smallrye-mutiny/blob/master/.github/workflows/build-master.yml#L17

**Comment by radcortez** [comment]
Lets fix Parent, release and fix this one.

**Comment by dmlloyd** [comment]
> @dmlloyd you can use a matrix as I did for mutiny:
> https://github.com/smallrye/smallrye-mutiny/blob/master/.github/workflows/build-master.yml#L17

In this case we explicitly do *not* want a matrix.  The POM already knows how to test with each JDK, and using a matrix will dramatically increase the amount of time it takes to build the project; anyway, to properly use the SmallRye MR JAR support, the POM must only be run by the latest supported JDK.

**Comment by dmlloyd** [comment]
I guess then this is waiting for smallrye/smallrye-parent#149 to get merged so we can do a release of that project, bump up the version here, and get a green board for merging.

**Pull request merged**
